FROM archlinux/base

RUN pacman -Syu --noconfirm

COPY ./requirePackages.name /root/

# RUN cat /root/requirePackages.name
RUN pacman -S $(< /root/requirePackages.name) --noconfirm

RUN git clone https://github.com/terryding77/dotfiles /root/dotfiles

WORKDIR /root/

CMD [ "zsh" ]
