source ~/.vim/settings/vim-plug.vim
source ~/.vim/settings/basic.vim
source ~/.vim/settings/common.vim
source ~/.vim/settings/lang-cxx.vim
source ~/.vim/settings/lang-go.vim
source ~/.vim/settings/lang-python.vim
source ~/.vim/settings/lang-jsx.vim
