" load plugins
source ~/.vim/settings/plugins.vim

" set configs
""""" appearance coding operation
source ~/.vim/settings/configs.vim

" add key maps (set at last to ensure usable)
source ~/.vim/settings/keymaps.vim
